import type { Metadata } from 'next'
import { Saira } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'

const saira = Saira({ 
  subsets: ['latin'],

  weight:['300','400','500','600']

 })

export const metadata: Metadata = {
  title: 'Cappucino',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
